# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: SHIFT-Task-Force.privacy.examples
canonical: http://SHIFT-Task-Force.github.io/demo-fhir-data
name: ShiftPrivacyExamples
title: "SHIFT Privacy Examples"
description: "A FHIR Implementation Guide containing example FHIR resources demonstrating privacy labeling using Security Labels and example ValueSets for sensitive data."
status: active
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2025+
releaseLabel: ci-build
publisher:
  name: SHIFT-Task-Force
  url: http://shift-project.org
license: CC-BY-4.0
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#001'

parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - fsh-generated/resources
#  path-pages:
#    - input/pagecontent
#    - fsh-generated/includes
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'

#dependencies:
#  hl7.fhir.us.core: 4.0.0
#  hl7.fhir.us.core: current
#  ihe.iti.pcf: 1.1.0
#  hl7.xprod.uv.gender-harmony: current

# ╭────────────────────────────────────────────pages───────────────────────────────────────────────╮
# │  The pages property corresponds to IG.definition.page.                                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
pages:
  index.md:
    title: "SHIFT IG Home"
  behavioral.md:
    title: "Behavioral Health Use Case"
  Adolescent2.md:
    title: "Adolescent Use Case"
  MaxineMayfield.md:
    title: "Maxine Mayfield at 16"
  MonicaRambeau.md:
    title: "Monica Rambeau at 19"
  VeronicaMars.md:
    title: "Veronica Mars"
  download.md:
    title: "About and Download"


# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Use-Cases:
    Behavioral-Health: behavioral.html
    Adolescent: Adolescent2.html
    Veronica Mars: VeronicaMars.html
  Artifacts: artifacts.html
  About: download.html

groups:
  CarlFredericksonCareTeam:
    description: "Resources related to Carl Frederickson's Care Team"
    resources:
      - PractitionerRole/DrHibbert-pcp
      - Practitioner/DrHibbert
      - Organization/SpringfieldMedicalCenter
      - PractitionerRole/DrFunke-psychiatrist
      - Practitioner/DrFunke
      - PractitionerRole/LucyvanPelt-therapist
      - Practitioner/LucyvanPelt
      - PractitionerRole/DrWhite-psychiatrist
      - Practitioner/DrWhite
      - Organization/SpringfieldMedicalCenterAddictionProgram
      - Organization/OrthopedicHealthServices
      - PractitionerRole/DrSasquatch-podiatrist
      - Practitioner/DrSasquatch
      - Organization/RegionalAdvancedDiagnosticServices
      - PractitionerRole/DrBanner-radiologist
      - Practitioner/DrBanner
      - PractitionerRole/DrAurora-anesthesiologist
      - Practitioner/DrAurora
      - PractitionerRole/ACOCareManager-practitionerrole
      - Practitioner/ACO-Care-Manager
      - Organization/SpringfieldACO
      - RelatedPerson/EllieFrederickson
      - Organization/CarlFredericksonBLP
      - Organization/CarlFredericksonMapple
      - Organization/CarlFredericksonMedicare
      - Organization/CarlFredericksonGreenInc
      - Bundle/AllofCarlTeam
  CarlFrederickson:
    description: "Resources related to Carl Frederickson"
    resources:
      - Patient/CarlFrederickson
      - CareTeam/CarlFredericksonCareTeam
      - Observation/CarlFredericksonPHQ9
      - Observation/CarlFredericksonPHQ9A  
      - Condition/CarlFredericksonBunions
      - Condition/CarlFredericksonHTN
      - Condition/CarlFredericksonMDD
      - Condition/CarlFredericksonOCPD
      - Condition/CarlFredericksonOUD
      - DiagnosticReport/CarlFredericksonXrayFeet
      - MedicationRequest/CarlFredericksonBuprenorphineNaltrexone
      - MedicationRequest/CarlFredericksonCaptopril
      - MedicationRequest/CarlFredericksonFluoxetine
      - MedicationRequest/CarlFredericksonIbuprofen
      - Observation/CarlFredericksonBloodPressure
      - Observation/CarlFredericksonOUDThoughtRecord
      - Consent/CarlFredericksonConsent
      - Consent/CarlFrederickson42CFRPartIIConsent
      - Bundle/AllOfCarlFrederickson
  MonicaRambeau:
    description: "Resources related to Monica Rambeau"
    resources:
      - Patient/MonicaRambeau
      - Observation/MonicaRambeauSexualOrientation
      - Condition/MonicaRambeauChronicConstipation
      - Condition/MonicaRambeauAsthma
      - Condition/MonicaRambeauIrregularPeriods
      - Condition/MonicaRambeauChlamydia
      - Condition/MonicaRambeauMedicalAbortion
      - Condition/MonicaRambeauDandCAbortion
      - Procedure/MonicaRambeauDandCProcedure
      - DiagnosticReport/MonicaRambeauGCNAAT
      - DiagnosticReport/MonicaRambeauHIVELISA
      - MedicationRequest/MonicaRambeauMiralax
      - MedicationRequest/MonicaRambeauAlbuterol
      - MedicationRequest/MonicaRambeauPulmicort
      - MedicationRequest/MonicaRambeauLoestrin
      - MedicationRequest/MonicaRambeauAzithromycin
      - MedicationRequest/MonicaRambeauDescovy
      - MedicationRequest/MonicaRambeauMifepristone
      - MedicationRequest/MonicaRambeauMisoprostol
      - DiagnosticReport/MonicaRambeauFirstTrimesterUS
      - DiagnosticReport/MonicaRambeauQuadScreen
      - Observation/MonicaRambeauOBHx
      - Observation/MonicaRambeauLMP
      - Observation/MonicaRambeauPOChCG
      - Observation/MonicaRambeauhCGSerumQuantDandC
      - Observation/MonicaRambeauhCGSerumQuantMedAbort
      - AllergyIntolerance/MonicaRambeauAmoxicillinAllergy
      - RelatedPerson/MariaRambeau
      - RelatedPerson/FrankRambeau
      - Practitioner/MonicaRambeauDoctor
      - Organization/MonicaRambeauBLP
      - Organization/MonicaRambeauTPL
      - Practitioner/MonicaRambeauRiviera
      - Practitioner/MonicaRambeauMcStuffins
      - Organization/MonicaRambeauBBP
      - Organization/MonicaRambeauMapple
      - Organization/MonicaRambeauGreen
      - Consent/MonicaRambeauFamilyConsent
      - Consent/MonicaRambeauTreatmentConsent
      - Bundle/AllOfMonicaRambeau
  MaxineMayfield:
    description: "Resources related to Maxine Mayfield (age 16)"
    resources:
      - Patient/MaxineMayfield16
      - Observation/MaxineMayfield16SexualOrientation
      - Condition/MaxineMayfield16ChronicConstipation
      - Condition/MaxineMayfield16Asthma
      - Condition/MaxineMayfield16IrregularPeriods
      - Condition/MaxineMayfield16Chlamydia
      - Condition/MaxineMayfield16MedicalAbortion
      - Condition/MaxineMayfield16DandCAbortion
      - Procedure/MaxineMayfield16DandCProcedure
      - DiagnosticReport/MaxineMayfield16GCNAAT
      - DiagnosticReport/MaxineMayfield16HIVELISA
      - MedicationRequest/MaxineMayfield16Miralax
      - MedicationRequest/MaxineMayfield16Albuterol
      - MedicationRequest/MaxineMayfield16Pulmicort
      - MedicationRequest/MaxineMayfield16Loestrin
      - MedicationRequest/MaxineMayfield16Azithromycin
      - MedicationRequest/MaxineMayfield16Descovy
      - MedicationRequest/MaxineMayfield16Mifepristone
      - MedicationRequest/MaxineMayfield16Misoprostol
      - DiagnosticReport/MaxineMayfield16FirstTrimesterUS
      - DiagnosticReport/MaxineMayfield16QuadScreen
      - Observation/MaxineMayfield16OBHx
      - Observation/MaxineMayfield16LMP
      - Observation/MaxineMayfield16POChCG
      - Observation/MaxineMayfield16hCGSerumQuantDandC
      - Observation/MaxineMayfield16hCGSerumQuantMedAbort
      - AllergyIntolerance/MaxineMayfield16AmoxicillinAllergy
      - RelatedPerson/SueHargrove16
      - RelatedPerson/SamMayfield16
      - Practitioner/MaxineMayfieldDoctor
      - Consent/MaxineMayfield16FamilyConsent
      - Consent/MaxineMayfield16TreatmentConsent
      - Bundle/AllOfMaxineMayfield16
  VeronicaMars:
    description: "Resources related to Veronica Mars"
    resources:
      - Patient/VeronicaMars
      - Condition/VeronicaMarsAtopicDermatitis
      - Condition/VeronicaMarsFoodInsecurity
      - Condition/VeronicaMarsHousingInstability
      - Condition/VeronicaMarsFinancialInsecurity
      - Condition/VeronicaMarsIPV
      - Condition/VeronicaMarsElevatedBP
      - Condition/VeronicaMarsCreatinine
      - Condition/VeronicaMarsProteinuria
      - Condition/VeronicaMarsHematuria
      - Condition/VeronicaMarsCSAHx
      - Encounter/VeronicaMarsEncSMC2wk
      - Condition/VeronicaMarsWellAdultExam
      - Encounter/VeronicaMarsEncOHSED
      - Condition/VeronicaMarsIPVOHSEnc
      - Encounter/VeronicaMarsEncSMCToday
      - Condition/VeronicaMarsIPVSMCToday
      - Observation/VeronicaMarsEmploymentStatus
      - DiagnosticReport/VeronicaMarsBMP
      - DiagnosticReport/VeronicaMarsUA
      - MedicationRequest/VeronicaMarsHydrocortisone
      - RelatedPerson/LucasCage
      - Practitioner/VeronicaMarsDoctor
      - Bundle/AllOfVeronicaMars



