# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: SHIFT-Task-Force.privacy.examples
canonical: http://SHIFT-Task-Force.github.io/demo-fhir-data
name: ShiftPrivacyExamples
title: "SHIFT Privacy Examples"
description: "A FHIR Implementation Guide containing example FHIR resources demonstrating privacy labeling using Security Labels and example ValueSets for sensitive data."
status: active
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2025+
releaseLabel: ci-build
publisher:
  name: SHIFT-Task-Force
  url: http://shift-project.org
license: CC-BY-4.0
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#001'

parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - fsh-generated/resources
#  path-pages:
#    - input/pagecontent
#    - fsh-generated/includes
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'

#dependencies:
#  hl7.fhir.us.core: 4.0.0
#  hl7.fhir.us.core: current
#  ihe.iti.pcf: 1.1.0
#  hl7.xprod.uv.gender-harmony: current

# ╭────────────────────────────────────────────pages───────────────────────────────────────────────╮
# │  The pages property corresponds to IG.definition.page.                                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
pages:
  index.md:
    title: "SHIFT IG Home"
  behavioral.md:
    title: "Behavioral Health Use Case"
  adolescent.md:
    title: "Adolescent Use Case"
  Rambeau.md:
    title: "Background on Rambeau Sisters"
  SteffiRambeau.md:
    title: "Steffi Rambeau at 16"
  MonicaRambeau.md:
    title: "Monica Rambeau at 19"
  VeronicaMars.md:
    title: "Veronica Mars"
  download.md:
    title: "About and Download"


# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Use-Cases:
    Adolescent: adolescent.html
    Behavioral-Health: behavioral.html
    Rambeau Sisters: Rambeau.html
    Veronica Mars: VeronicaMars.html
  Artifacts: artifacts.html
  About: download.html

groups:
  CarlFredericksonCareTeam:
    description: "Resources related to Carl Frederickson's Care Team"
    resources:
      - PractitionerRole/DrHibbert-pcp
      - Practitioner/DrHibbert
      - Organization/SpringfieldMedicalCenter
      - PractitionerRole/DrFunke-psychiatrist
      - Practitioner/DrFunke
      - PractitionerRole/LucyvanPelt-therapist
      - Practitioner/LucyvanPelt
      - PractitionerRole/DrWhite-psychiatrist
      - Practitioner/DrWhite
      - Organization/SpringfieldMedicalCenterAddictionProgram
      - Organization/OrthopedicHealthServices
      - PractitionerRole/DrSasquatch-podiatrist
      - Practitioner/DrSasquatch
      - Organization/RegionalAdvancedDiagnosticServices
      - PractitionerRole/DrBanner-radiologist
      - Practitioner/DrBanner
      - PractitionerRole/DrAurora-anesthesiologist
      - Practitioner/DrAurora
      - PractitionerRole/ACOCareManager-practitionerrole
      - Practitioner/ACO-Care-Manager
      - Organization/SpringfieldACO
      - Bundle/AllofCarlTeam
  CarlFrederickson:
    description: "Resources related to Carl Frederickson"
    resources:
      - Patient/CarlFrederickson
      - CareTeam/CarlFredericksonCareTeam
      - Observation/CarlFredericksonPHQ9
      - Observation/CarlFredericksonPHQ9A  
      - Condition/CarlFredericksonBunions
      - Condition/CarlFredericksonHTN
      - Condition/CarlFredericksonMDD
      - Condition/CarlFredericksonOCPD
      - Condition/CarlFredericksonOUD
      - DiagnosticReport/CarlFredericksonXrayFeet
      - MedicationRequest/CarlFredericksonBuprenorphineNaltrexone
      - MedicationRequest/CarlFredericksonCaptopril
      - MedicationRequest/CarlFredericksonFluoxetine
      - MedicationRequest/CarlFredericksonIbuprofen
      - Observation/CarlFredericksonBloodPressure
      - Observation/CarlFredericksonOUDThoughtRecord
      - RelatedPerson/EllieFrederickson
      - Bundle/AllOfCarlFrederickson
  MonicaRambeau:
    description: "Resources related to Monica Rambeau"
    resources:
      - Patient/MonicaRambeau
      - Observation/MonicaRambeauSexualOrientation
      - Condition/MonicaRambeauChronicConstipation
      - Condition/MonicaRambeauAsthma
      - Condition/MonicaRambeauIrregularPeriods
      - Condition/MonicaRambeauChlamydia
      - Condition/MonicaRambeauMedicalAbortion
      - Condition/MonicaRambeauDandCAbortion
      - Procedure/MonicaRambeauDandCProcedure
      - DiagnosticReport/MonicaRambeauGCNAAT
      - DiagnosticReport/MonicaRambeauHIVELISA
      - MedicationRequest/MonicaRambeauMiralax
      - MedicationRequest/MonicaRambeauAlbuterol
      - MedicationRequest/MonicaRambeauPulmicort
      - MedicationRequest/MonicaRambeauLoestrin
      - MedicationRequest/MonicaRambeauAzithromycin
      - MedicationRequest/MonicaRambeauDescovy
      - MedicationRequest/MonicaRambeauMifepristone
      - MedicationRequest/MonicaRambeauMisoprostol
      - DiagnosticReport/MonicaRambeauFirstTrimesterUS
      - DiagnosticReport/MonicaRambeauQuadScreen
      - Observation/MonicaRambeauOBHx
      - Observation/MonicaRambeauLMP
      - RelatedPerson/MariaRambeau
      - RelatedPerson/FrankRambeau
      - Practitioner/MonicaRambeauDoctor
      - Bundle/AllOfMonicaRambeau
  SteffiRambeau:
    description: "Resources related to Steffi Rambeau (age 16)"
    resources:
      - Patient/SteffiRambeau16
      - Observation/SteffiRambeau16SexualOrientation
      - Condition/SteffiRambeau16ChronicConstipation
      - Condition/SteffiRambeau16Asthma
      - Condition/SteffiRambeau16IrregularPeriods
      - Condition/SteffiRambeau16Chlamydia
      - Condition/SteffiRambeau16MedicalAbortion
      - Condition/SteffiRambeau16DandCAbortion
      - Procedure/SteffiRambeau16DandCProcedure
      - DiagnosticReport/SteffiRambeau16GCNAAT
      - DiagnosticReport/SteffiRambeau16HIVELISA
      - MedicationRequest/SteffiRambeau16Miralax
      - MedicationRequest/SteffiRambeau16Albuterol
      - MedicationRequest/SteffiRambeau16Pulmicort
      - MedicationRequest/SteffiRambeau16Loestrin
      - MedicationRequest/SteffiRambeau16Azithromycin
      - MedicationRequest/SteffiRambeau16Descovy
      - MedicationRequest/SteffiRambeau16Mifepristone
      - MedicationRequest/SteffiRambeau16Misoprostol
      - DiagnosticReport/SteffiRambeau16FirstTrimesterUS
      - DiagnosticReport/SteffiRambeau16QuadScreen
      - Observation/SteffiRambeau16OBHx
      - Observation/SteffiRambeau16LMP
      - RelatedPerson/MariaRambeau16
      - RelatedPerson/FrankRambeau16
      - Practitioner/SteffiRambeauDoctor
      - Bundle/AllOfSteffiRambeau16
  VeronicaMars:
    description: "Resources related to Veronica Mars"
    resources:
      - Patient/VeronicaMars
      - Condition/VeronicaMarsAtopicDermatitis
      - Condition/VeronicaMarsFoodInsecurity
      - Condition/VeronicaMarsHousingInstability
      - Condition/VeronicaMarsFinancialInsecurity
      - Condition/VeronicaMarsIPV
      - Condition/VeronicaMarsElevatedBP
      - Condition/VeronicaMarsCreatinine
      - Condition/VeronicaMarsProteinuria
      - Condition/VeronicaMarsHematuria
      - Condition/VeronicaMarsCSAHx
      - Encounter/VeronicaMarsEncSMC2wk
      - Condition/VeronicaMarsWellAdultExam
      - Encounter/VeronicaMarsEncOHSED
      - Condition/VeronicaMarsIPVOHSEnc
      - Encounter/VeronicaMarsEncSMCToday
      - Condition/VeronicaMarsIPVSMCToday
      - Observation/VeronicaMarsEmploymentStatus
      - DiagnosticReport/VeronicaMarsBMP
      - DiagnosticReport/VeronicaMarsUA
      - MedicationRequest/VeronicaMarsHydrocortisone
      - RelatedPerson/LucasCage
      - Practitioner/VeronicaMarsDoctor
      - Bundle/AllOfVeronicaMars



